# Generated by Django 5.1 on 2024-10-29 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountingapp', '0004_bill_user_category_user_item_user_parties_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
